### PR TITLE
Bump EdgeDB to 1.0

### PR DESCRIPTION
**Pull request by ambv**

### CODE REVIEW

**Review by elprans — APPROVED** [review]
Keeping up! :-)

**Comment by ambv** [comment]
I can't merge it myself, you'll have to click the button :-)

**Comment by elprans** [comment]
Sorry, old habits :-)  I've made you a collaborator on this repo.

**Comment by ambv** [comment]
Thanks! I'd have to also get write access to land the change:

Screen Shot 2022-02-10 at 17 54 52

**Pull request merged**
